# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NouvelleOperation.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All fff changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Operation(object):
    def setupUi(self, Operation):
        Operation.setObjectName("Operation")
        Operation.resize(612, 602)
        Operation.setMinimumSize(QtCore.QSize(612, 602))
        Operation.setMaximumSize(QtCore.QSize(612, 602))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("bin/DPFL - LOGO.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Operation.setWindowIcon(icon)
        self.buttonBox = QtWidgets.QDialogButtonBox(Operation)
        self.buttonBox.setGeometry(QtCore.QRect(240, 560, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget = QtWidgets.QWidget(Operation)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 20, 541, 521))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.TextOperationLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.TextOperationLabel.setObjectName("TextOperationLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.TextOperationLabel)
        self.OperationLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.OperationLineEdit.setObjectName("OperationLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.OperationLineEdit)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.BVLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.BVLabel.setObjectName("BVLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.BVLabel)
        self.surfaceDuBassinVersantLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.surfaceDuBassinVersantLineEdit.setObjectName("surfaceDuBassinVersantLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.surfaceDuBassinVersantLineEdit)
        self.coefficientDApportLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.coefficientDApportLabel.setObjectName("coefficientDApportLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.coefficientDApportLabel)
        self.coefficientDApportLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.coefficientDApportLineEdit.setObjectName("coefficientDApportLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.coefficientDApportLineEdit)
        self.surfaceActiveLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.surfaceActiveLabel.setObjectName("surfaceActiveLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.surfaceActiveLabel)
        self.surfaceActiveLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.surfaceActiveLineEdit.setObjectName("surfaceActiveLineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.surfaceActiveLineEdit)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label)
        self.longueurLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.longueurLabel.setObjectName("longueurLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.longueurLabel)
        self.longueurLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.longueurLineEdit.setObjectName("longueurLineEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.longueurLineEdit)
        self.altitudeAmontLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.altitudeAmontLabel.setObjectName("altitudeAmontLabel")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.altitudeAmontLabel)
        self.altitudeAmontLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.altitudeAmontLineEdit.setObjectName("altitudeAmontLineEdit")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.altitudeAmontLineEdit)
        self.altitudeAvalLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.altitudeAvalLabel.setObjectName("altitudeAvalLabel")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.altitudeAvalLabel)
        self.altitudeAvalLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.altitudeAvalLineEdit.setObjectName("altitudeAvalLineEdit")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.altitudeAvalLineEdit)
        self.penteMoyenneLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.penteMoyenneLabel.setObjectName("penteMoyenneLabel")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.penteMoyenneLabel)
        self.penteMoyenneLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.penteMoyenneLineEdit.setObjectName("penteMoyenneLineEdit")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.penteMoyenneLineEdit)
        self.dBitDeFuiteAutorisLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.dBitDeFuiteAutorisLabel.setObjectName("dBitDeFuiteAutorisLabel")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.dBitDeFuiteAutorisLabel)
        self.dBitDeFuiteAutorisLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.dBitDeFuiteAutorisLineEdit.setObjectName("dBitDeFuiteAutorisLineEdit")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.dBitDeFuiteAutorisLineEdit)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.ouiLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.ouiLabel.setObjectName("ouiLabel")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.ouiLabel)
        self.VidangeouiRadioButton = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.VidangeouiRadioButton.setObjectName("VidangeouiRadioButton")
        self.buttonGroup = QtWidgets.QButtonGroup(Operation)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.VidangeouiRadioButton)
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.VidangeouiRadioButton)
        self.VidangenonRadioButton = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.VidangenonRadioButton.setObjectName("VidangenonRadioButton")
        self.buttonGroup.addButton(self.VidangenonRadioButton)
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.VidangenonRadioButton)
        self.coefficientMajorateurLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.coefficientMajorateurLabel.setObjectName("coefficientMajorateurLabel")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.coefficientMajorateurLabel)
        self.coefficientMajorateurLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.coefficientMajorateurLineEdit.setObjectName("coefficientMajorateurLineEdit")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.coefficientMajorateurLineEdit)
        self.coefficientDeSCuritLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.coefficientDeSCuritLabel.setObjectName("coefficientDeSCuritLabel")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.LabelRole, self.coefficientDeSCuritLabel)
        self.coefficientDeSCuritLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.coefficientDeSCuritLineEdit.setObjectName("coefficientDeSCuritLineEdit")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.FieldRole, self.coefficientDeSCuritLineEdit)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(18, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(19, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.terrainNaturelLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.terrainNaturelLabel.setObjectName("terrainNaturelLabel")
        self.formLayout.setWidget(20, QtWidgets.QFormLayout.LabelRole, self.terrainNaturelLabel)
        self.terrainNaturelLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.terrainNaturelLineEdit.setObjectName("terrainNaturelLineEdit")
        self.formLayout.setWidget(20, QtWidgets.QFormLayout.FieldRole, self.terrainNaturelLineEdit)
        self.nappePhrAtiqueLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.nappePhrAtiqueLabel.setObjectName("nappePhrAtiqueLabel")
        self.formLayout.setWidget(21, QtWidgets.QFormLayout.LabelRole, self.nappePhrAtiqueLabel)
        self.nappePhrAtiqueLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.nappePhrAtiqueLineEdit.setObjectName("nappePhrAtiqueLineEdit")
        self.formLayout.setWidget(21, QtWidgets.QFormLayout.FieldRole, self.nappePhrAtiqueLineEdit)
        self.coefficientDePermAbilitLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.coefficientDePermAbilitLabel.setObjectName("coefficientDePermAbilitLabel")
        self.formLayout.setWidget(22, QtWidgets.QFormLayout.LabelRole, self.coefficientDePermAbilitLabel)
        self.coefficientDePermAbilitLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.coefficientDePermAbilitLineEdit.setObjectName("coefficientDePermAbilitLineEdit")
        self.formLayout.setWidget(22, QtWidgets.QFormLayout.FieldRole, self.coefficientDePermAbilitLineEdit)
        self.nonLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.nonLabel.setObjectName("nonLabel")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.nonLabel)

        self.retranslateUi(Operation)
        self.buttonBox.accepted.connect(Operation.accept)
        self.buttonBox.rejected.connect(Operation.reject)
        QtCore.QMetaObject.connectSlotsByName(Operation)

    def retranslateUi(self, Operation):
        _translate = QtCore.QCoreApplication.translate
        Operation.setWindowTitle(_translate("Operation", "Nouvelle operation"))
        self.TextOperationLabel.setText(_translate("Operation", "Désignation de l\'opération"))
        self.label_4.setText(_translate("Operation", "Bassin versant"))
        self.BVLabel.setText(_translate("Operation", "Surface du bassin versant"))
        self.coefficientDApportLabel.setText(_translate("Operation", "Coefficient d\'apport"))
        self.surfaceActiveLabel.setText(_translate("Operation", "Surface active"))
        self.label.setText(_translate("Operation", "Dimension"))
        self.longueurLabel.setText(_translate("Operation", "Longueur"))
        self.altitudeAmontLabel.setText(_translate("Operation", "Altitude amont"))
        self.altitudeAvalLabel.setText(_translate("Operation", "Altitude Aval"))
        self.penteMoyenneLabel.setText(_translate("Operation", "Pente moyenne"))
        self.dBitDeFuiteAutorisLabel.setText(_translate("Operation", "Débit de fuite autorisé"))
        self.label_2.setText(_translate("Operation", "Débit de vidange constant :"))
        self.ouiLabel.setText(_translate("Operation", "Oui"))
        self.coefficientMajorateurLabel.setText(_translate("Operation", "Coefficient majorateur"))
        self.coefficientDeSCuritLabel.setText(_translate("Operation", "Coefficient de sécurité"))
        self.label_3.setText(_translate("Operation", "Caracteristique du site"))
        self.terrainNaturelLabel.setText(_translate("Operation", "Terrain naturel"))
        self.nappePhrAtiqueLabel.setText(_translate("Operation", "Nappe Phréatique"))
        self.nappePhrAtiqueLineEdit.setInputMask(_translate("Operation", "999.999"))
        self.coefficientDePermAbilitLabel.setText(_translate("Operation", "Coefficient de perméabilité"))
        self.nonLabel.setText(_translate("Operation", "Non"))
